sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ametsoro/docker-react-tuto -f Dockerfile.dev .

# script:
  # - docker run ametsoro/docker-react-tuto npm run test -- --coverage

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-tuto"
  env: "Dockerreacttuto-env"
  bucket_name: "elasticbeanstalk-us-east-2-114194448940"
  bucket_path: "test-travis-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  # secret_access_key:
  #   secure: "$AWS_SECRET_KEY"